export const REQUEST_BOOKABLES = 'REQUEST_BOOKABLES'
export const REQUEST_BOOKABLES_FAILED = 'REQUEST_BOOKABLES_FAILED'
export const RECEIVE_BOOKABLES = 'RECEIVE_BOOKABLES'

export const REQUEST_BOOKINGS = 'REQUEST_BOOKINGS'
export const REQUEST_BOOKINGS_FAILED = 'REQUEST_BOOKINGS_FAILED'
export const RECEIVE_BOOKINGS = 'RECEIVE_BOOKINGS'

export const REQUEST_LOCATIONS = 'REQUEST_LOCATIONS'
export const RECEIVE_LOCATIONS = 'RECEIVE_LOCATIONS'
export const REQUEST_LOCATIONS_FAILED = 'REQUEST_LOCATIONS_FAILED'

export const BOOKING_SUCCESS = 'BOOKING_SUCCESS'
export const BOOKING_FAIL = 'BOOKING_FAIL'

export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'

export const SET_TOKEN = 'SET_TOKEN'
export const REMOVE_TOKEN = 'REMOVE_TOKEN'

export const SET_ERROR = 'SET_ERROR'
export const REMOVE_ERROR = 'REMOVE_ERROR'
