export const RECEIVE_BOOKABLES = 'RECEIVE_BOOKABLES'
export const RECEIVE_BOOKINGS = 'RECEIVE_BOOKINGS'
export const RECEIVE_LOCATIONS = 'RECEIVE_LOCATIONS'

export const BOOKING_SUCCESS = 'BOOKING_SUCCESS'
export const BOOKING_FAIL = 'BOOKING_FAIL'

export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'

export const SET_TOKEN = 'SET_TOKEN'
export const REMOVE_TOKEN = 'REMOVE_TOKEN'

export const SET_ERROR = 'SET_ERROR'
export const REMOVE_ERROR = 'REMOVE_ERROR'
