---
resource_types:
  - name: npm-cache
    type: docker-image
    source:
      repository: benaychh/npm-dependency-cache
      tag: "latest"
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
- name: bookit-mobile
  type: git
  source: &repo-source
    uri: https://github.com/saoirse-zee/bookit-mobile
    branch: {{BRANCH}}
- name: dependency-cache
  type: npm-cache
  source:
    <<: *repo-source
    yarn-support: true
    paths:
      - package.json
- name: slack-alert
  type: slack-notification
  source:
    url: {{SLACK_NOTIFY_URL}}

jobs:
- name: Install Dependencies
  build_logs_to_retain: 3
  plan:
    - get: bookit-mobile
      trigger: true
    - get: dependency-cache
- name: Lint Bookit-Mobile Code Base
  build_logs_to_retain: 3
  plan:
    - get: bookit-mobile
      trigger: true
      passed:
        - Install Dependencies
    - get: dependency-cache
    - &handle-dependencies
      task: handle dependencies
      file: bookit-mobile/concourse/tasks/dependencies.yml
      params:
        BOOKIT_API_BASE_URL: {{BOOKIT_API_BASE_URL_INTEGRATION}}
        MS_AUTH_STATE: {{MS_AUTH_STATE}}
        MS_AUTH_CLIENT_ID: {{MS_AUTH_CLIENT_ID}}
        MS_AUTH_REDIRECT_URL: https://auth.expo.io/@buildit/bookit-mobile-integration
    - task: lint the project
      file: bookit-mobile/concourse/tasks/lint.yml
  on_failure: &failure
    do:
      - task: Get Commit Info
        file: bookit-mobile/concourse/tasks/get_commit_info.yml
        params:
          GIT_COMMIT_URL: {{GIT_COMMIT_URL}}
          BRANCH: {{BRANCH}}
          STATUS: FAILED
          COLOR: danger
          FOLDER_NAME: bookit-mobile
          REPORTS_URL: {{REPORTS_URL}}
      - put: slack-alert
        params:
          text: |
            Error at step [<https://concourse.buildit.tools/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_JOB_NAME>]
          attachments_file: ./commit_info/attachments.json
- name: Run Unit Tests
  build_logs_to_retain: 3
  plan:
    - get: bookit-mobile
      trigger: true
      passed:
        - Install Dependencies
    - get: dependency-cache
    - *handle-dependencies
    - task: run the unit tests
      params:
        AWS_ACCESS_KEY: {{AWS_ACCESS_KEY}}
        AWS_SECRET_KEY: {{AWS_SECRET_KEY}}
        AWS_REGION: us-west-2
        BUCKET: {{AWS_BUCKET}}
      file: bookit-mobile/concourse/tasks/run_unit_tests.yml
  on_failure: *failure
- name: Publish to Staging
  build_logs_to_retain: 3
  plan:
    - get: bookit-mobile
      trigger: true
      passed:
        - Run Unit Tests
        - Lint Bookit-Mobile Code Base
    - get: dependency-cache
    - task: handle dependencies
      file: bookit-mobile/concourse/tasks/dependencies.yml
      params:
        BOOKIT_API_BASE_URL: {{BOOKIT_API_BASE_URL_STAGING}}
        MS_AUTH_STATE: {{MS_AUTH_STATE}}
        MS_AUTH_CLIENT_ID: {{MS_AUTH_CLIENT_ID}}
        MS_AUTH_REDIRECT_URL: https://auth.expo.io/@buildit/bookit-mobile-staging-1
    - task: Publish
      params:
        EXPO_USERNAME: {{EXPO_USERNAME}}
        EXPO_PASSWORD: {{EXPO_PASSWORD}}
        CONFIG_FILE: staging.json
      file: bookit-mobile/concourse/tasks/publish.yml
  on_failure: *failure
- name: Notify Slack
  build_logs_to_retain: 3
  plan:
    - get: bookit-mobile
      trigger: true
      passed:
        - Publish to Staging
    - task: Get Commit Info
      params:
        GIT_COMMIT_URL: {{GIT_COMMIT_URL}}
        BRANCH: {{BRANCH}}
        STATUS: SUCCEEDED
        COLOR: good
        FOLDER_NAME: bookit-mobile
        REPORTS_URL: {{REPORTS_URL}}
      file: bookit-mobile/concourse/tasks/get_commit_info.yml
    - put: slack-alert
      params:
        text: |
          Successfully built [<https://concourse.buildit.tools/teams/bookit-mobile/pipelines/bookit-mobile|Bookit Mobile>]
        attachments_file: ./commit_info/attachments.json
