---
resource_types:
  - name: npm-cache
    type: docker-image
    source:
      repository: ymedlop/npm-cache-resource
      tag: "latest"
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
- name: bookit-mobile
  type: git
  source: &repo-source
    uri: https://github.com/saoirse-zee/bookit-mobile
    branch: unit-metrics
- name: dependency-cache
  type: npm-cache
  source:
    <<: *repo-source
    paths:
      - package.json
- name: slack-alert
  type: slack-notification
  source:
    url: {{SLACK_NOTIFY_URL}}

jobs:
- name: Install Dependencies
  build_logs_to_retain: 3
  plan:
    - get: bookit-mobile
      trigger: true
- name: Lint Bookit-Mobile Code Base
  build_logs_to_retain: 3
  plan:
    - get: bookit-mobile
      trigger: true
      passed:
        - Install Dependencies
    - get: dependency-cache
    - &handle-dependencies
      task: handle dependencies
      file: bookit-mobile/concourse/tasks/dependencies.yml
      params:
        BOOKIT_API_BASE_URL: {{BOOKIT_API_BASE_URL_INTEGRATION}}
    - task: lint the project
      file: bookit-mobile/concourse/tasks/lint.yml
  on_failure: &failure
    do:
      - task: Get Commit Info
        file: bookit-mobile/concourse/tasks/get_commit_info.yml
        params:
          GIT_COMMIT_URL: {{GIT_COMMIT_URL}}
          BRANCH: {{BRANCH}}
          STATUS: FAILED
          COLOR: danger
          FOLDER_NAME: bookit-mobile
      - put: slack-alert
        params:
          text: |
            Error at step [<https://concourse.buildit.tools/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_JOB_NAME>]
          attachments_file: ./commit_info/attachments.json
- name: Run Unit Tests
  build_logs_to_retain: 3
  plan:
    - get: bookit-mobile
      trigger: true
      passed:
        - Install Dependencies
    - get: dependency-cache
    - *handle-dependencies
    - task: run the unit tests
      params:
        AWS_ACCESS_KEY: {{AWS_ACCESS_KEY}}
        AWS_SECRET_KEY: {{AWS_SECRET_KEY}}
        AWS_REGION: us-west-2
        BUCKET: {{AWS_BUCKET}}
      file: bookit-mobile/concourse/tasks/run_unit_tests.yml
  on_failure: *failure
- name: Publish Integration Testing Code
  build_logs_to_retain: 3
  plan:
    - get: bookit-mobile
      trigger: true
      passed:
        - Lint Bookit-Mobile Code Base
        - Run Unit Tests
    - get: dependency-cache
    - *handle-dependencies
    - task: Publish New Code
      params:
        EXPO_USERNAME: {{EXPO_USERNAME}}
        EXPO_PASSWORD: {{EXPO_PASSWORD}}
        CONFIG_FILE: integration.json
      file: bookit-mobile/concourse/tasks/publish.yml
  on_failure: *failure
- name: Android Integration Tests
  plan:
    - get: bookit-mobile
      trigger: true
      passed:
        - Publish Integration Testing Code
    - get: dependency-cache
    - *handle-dependencies
    - task: Test Android Project
      params:
        EXPO_USERNAME: {{EXPO_USERNAME}}
        EXPO_PASSWORD: {{EXPO_PASSWORD}}
        AWS_ACCESS_KEY: {{AWS_ACCESS_KEY}}
        AWS_SECRET_KEY: {{AWS_SECRET_KEY}}
        AWS_REGION: us-west-2
        PROJECT_ARN: {{PROJECT_ARN}}
        DEVICE_POOL_ARN: {{ANDROID_DEVICE_POOL_ARN}}
        DEVICE: Android
        BINARY: {{ANDROID_S3_BINARY}}
      file: bookit-mobile/concourse/tasks/integration_tests.yml
  on_failure: *failure
- name: iPhone Integration Tests
  plan:
    - get: bookit-mobile
      trigger: true
      passed:
        - Publish Integration Testing Code
    - get: dependency-cache
    - *handle-dependencies
    - task: Test iOS Project
      params:
        EXPO_USERNAME: {{EXPO_USERNAME}}
        EXPO_PASSWORD: {{EXPO_PASSWORD}}
        AWS_ACCESS_KEY: {{AWS_ACCESS_KEY}}
        AWS_SECRET_KEY: {{AWS_SECRET_KEY}}
        AWS_REGION: us-west-2
        PROJECT_ARN: {{PROJECT_ARN}}
        DEVICE_POOL_ARN: {{IPHONE_DEVICE_POOL_ARN}}
        DEVICE: iOS
        BINARY: {{IPHONE_S3_BINARY}}
      file: bookit-mobile/concourse/tasks/integration_tests.yml
  on_failure: *failure
- name: Publish to Beta
  build_logs_to_retain: 3
  plan:
    - get: bookit-mobile
      trigger: true
      passed:
        - Android Integration Tests
        - iPhone Integration Tests
    - get: dependency-cache
    - task: handle dependencies
      file: bookit-mobile/concourse/tasks/dependencies.yml
      params:
        BOOKIT_API_BASE_URL: {{BOOKIT_API_BASE_URL_PRODUCTION}}
    - task: Publish
      params:
        EXPO_USERNAME: {{EXPO_USERNAME}}
        EXPO_PASSWORD: {{EXPO_PASSWORD}}
        RELEASE_CHANNEL: v1-beta
      file: bookit-mobile/concourse/tasks/publish.yml
  on_failure: *failure
- name: Notify Slack
  build_logs_to_retain: 3
  plan:
    - get: bookit-mobile
      trigger: true
      passed:
        - Publish to Beta
    - task: Get Commit Info
      params:
        GIT_COMMIT_URL: {{GIT_COMMIT_URL}}
        BRANCH: {{BRANCH}}
        STATUS: SUCCEEDED
        COLOR: good
        FOLDER_NAME: bookit-mobile
      file: bookit-mobile/concourse/tasks/get_commit_info.yml
    - put: slack-alert
      params:
        text: |
          Successfully built [<https://concourse.buildit.tools/teams/bookit-mobile/pipelines/bookit-mobile|Bookit Mobile>]
        attachments_file: ./commit_info/attachments.json
