---
resource_types:
  - name: npm-cache
    type: docker-image
    source:
      repository: ymedlop/npm-cache-resource
      tag: "latest"
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
- name: bookit-prototype-3
  type: git
  source: &repo-source
    uri: https://github.com/saoirse-zee/bookit-prototype-3
    branch: {{BRANCH}}
- name: dependency-cache
  type: npm-cache
  source:
    <<: *repo-source
    paths:
      - package.json

jobs:
- name: Install Dependencies
  plan:
    - get: bookit-prototype-3
      trigger: true
    - get: dependency-cache
- name: Lint Bookit-Mobile Code Base
  plan:
    - get: bookit-prototype-3
      trigger: true
      passed:
        - Install Dependencies
    - get: dependency-cache
    - task: handle dependencies
      file: bookit-prototype-3/concourse/tasks/dependencies.yml
      params:
        BOOKIT_API_BASE_URL: {{BOOKIT_API_BASE_URL_INTEGRATION}}
    - task: lint the project
      file: bookit-prototype-3/concourse/tasks/lint.yml
- name: Run Unit Tests
  plan:
    - get: bookit-prototype-3
      trigger: true
      passed:
        - Install Dependencies
    - get: dependency-cache
    - task: handle dependencies
      file: bookit-prototype-3/concourse/tasks/dependencies.yml
      params:
        BOOKIT_API_BASE_URL: {{BOOKIT_API_BASE_URL_INTEGRATION}}
    - task: run the unit tests
      file: bookit-prototype-3/concourse/tasks/run_unit_tests.yml
- name: Build Android Image
  plan:
    - get: bookit-prototype-3
      trigger: true
      passed:
        - Lint Bookit-Mobile Code Base
        - Run Unit Tests
    - get: dependency-cache
    - task: handle dependencies
      file: bookit-prototype-3/concourse/tasks/dependencies.yml
      params:
        BOOKIT_API_BASE_URL: {{BOOKIT_API_BASE_URL_INTEGRATION}}
    - task: Build Android Project
      params:
        EXPO_USERNAME: {{EXPO_USERNAME}}
        EXPO_PASSWORD: {{EXPO_PASSWORD}}
      file: bookit-prototype-3/concourse/tasks/build_android.yml
- name: Build iPhone Image
  plan:
    - get: bookit-prototype-3
      trigger: true
      passed:
        - Lint Bookit-Mobile Code Base
        - Run Unit Tests
    - get: dependency-cache
    - task: handle dependencies
      file: bookit-prototype-3/concourse/tasks/dependencies.yml
      params:
        BOOKIT_API_BASE_URL: {{BOOKIT_API_BASE_URL_INTEGRATION}}
    - task: Build iPhone Project
      params:
        EXPO_USERNAME: {{EXPO_USERNAME}}
        EXPO_PASSWORD: {{EXPO_PASSWORD}}
      file: bookit-prototype-3/concourse/tasks/build_iphone.yml
- name: Test Android Image
  plan:
    - get: bookit-prototype-3
      trigger: true
      passed:
        - Build Android Image
    - get: dependency-cache
    - task: handle dependencies
      file: bookit-prototype-3/concourse/tasks/dependencies.yml
      params:
        BOOKIT_API_BASE_URL: {{BOOKIT_API_BASE_URL_INTEGRATION}}
    - task: Test Android Project
      params:
        EXPO_USERNAME: {{EXPO_USERNAME}}
        EXPO_PASSWORD: {{EXPO_PASSWORD}}
        AWS_ACCESS_KEY: {{DEVICEFARM_ACCESS_KEY}}
        AWS_SECRET_KEY: {{DEVICEFARM_SECRET_KEY}}
        AWS_REGION: us-west-2
        PROJECT_ARN: {{PROJECT_ARN}}
        DEVICE_POOL_ARN: {{ANDROID_DEVICE_POOL_ARN}}
      file: bookit-prototype-3/concourse/tasks/integration_tests_android.yml
- name: Test iPhone Image
  plan:
    - get: bookit-prototype-3
      trigger: true
      passed:
        - Build iPhone Image
    - get: dependency-cache
    - task: handle dependencies
      file: bookit-prototype-3/concourse/tasks/dependencies.yml
      params:
        BOOKIT_API_BASE_URL: {{BOOKIT_API_BASE_URL_INTEGRATION}}
    - task: Test iPhone Project
      params:
        EXPO_USERNAME: {{EXPO_USERNAME}}
        EXPO_PASSWORD: {{EXPO_PASSWORD}}
        AWS_ACCESS_KEY: {{DEVICEFARM_ACCESS_KEY}}
        AWS_SECRET_KEY: {{DEVICEFARM_SECRET_KEY}}
        AWS_REGION: us-west-2
        PROJECT_ARN: {{PROJECT_ARN}}
        DEVICE_POOL_ARN: {{IPHONE_DEVICE_POOL_ARN}}
      file: bookit-prototype-3/concourse/tasks/integration_tests_iphone.yml