platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
  - name: bookit-with-deps

run:
  path: bookit-with-deps/concourse/scripts/build_binary.sh