platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: carbon

inputs:
  - name: bookit-mobile
  - name: dependency-cache

outputs:
  - name: bookit-with-deps

run:
  path: bookit-mobile/concourse/scripts/dependencies.sh
