platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
  - name: bookit-prototype-3
  - name: dependency-cache

outputs:
  - name: bookit-with-deps

run:
  path: bookit-prototype-3/concourse/scripts/dependencies.sh