platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
  - name: bookit-prototype-3

outputs:
  - name: commit_info

run:
  path: bookit-prototype-3/concourse/scripts/get_commit_info.sh