platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
  - name: bookit-with-deps

outputs:
  - name: coverage

run:
  path: bookit-with-deps/concourse/scripts/run_unit_tests.sh